export default {
	"1": { "Skin_id": 1, "Skin_type": 1, "Unlock": 1, "Skin_name": "Rust", "Skin_description": "A ruthless mercenary who seeks to rebuild order through his strength.", "Monkey_spine": "dh_monkey_1", "Backpack_spine": "pub_1", "Dog_spine": "dh_dog_1", "Monkey_png": "Monkey_1", "Monkey_base": ["Monkey_base_1", "Monkey_base_1_1"], "Bg": "ui_common_bg1", "Bg_spine": "beijing", "Unlock_description": "" },
	"2": { "Skin_id": 2, "Skin_type": 2, "Unlock": 2, "Skin_name": "Halo", "Skin_description": "Born on a mysterious isolated island and mutated into a half-zombiehe， he seeks to break the curse.", "Monkey_spine": "dh_monkey_2", "Backpack_spine": "pub_2", "Dog_spine": "dh_dog_1", "Monkey_png": "Monkey_2", "Monkey_base": ["Monkey_base_2", "Monkey_base_2_1"], "Bg": "ui_common_bg1", "Bg_spine": "beijing", "Unlock_description": "Lv.2" },
	"3": { "Skin_id": 3, "Skin_type": 2, "Unlock": 3, "Skin_name": "Wukong", "Skin_description": "Wukong,  a descendant of Sun Wukong who aims to restore the spirit vein and fight against dark forces.", "Monkey_spine": "dh_monkey_3", "Backpack_spine": "pub_3", "Dog_spine": "dh_pig_1", "Monkey_png": "Monkey_3", "Monkey_base": ["Monkey_base_2", "Monkey_base_2_1"], "Bg": "ui_common_bg4", "Bg_spine": "beijing2", "Unlock_description": "Lv.3" },
	"4": { "Skin_id": 4, "Skin_type": 2, "Unlock": 4, "Skin_name": "Slice", "Skin_description": "Lazy yet smart,  he earns respect through his automated pizza delivery device.", "Monkey_spine": "dh_monkey_4", "Backpack_spine": "pub_4", "Dog_spine": "dh_dog_1", "Monkey_png": "Monkey_4", "Monkey_base": ["Monkey_base_2", "Monkey_base_2_1"], "Bg": "ui_common_bg1", "Bg_spine": "beijing", "Unlock_description": "Lv.4" },
	"5": { "Skin_id": 5, "Skin_type": 2, "Unlock": 5, "Skin_name": "GoldGlint", "Skin_description": "In pursuit of the treasure,  he embarks on adventures with charm and wisdom.", "Monkey_spine": "dh_monkey_5", "Backpack_spine": "pub_5", "Dog_spine": "dh_dog_1", "Monkey_png": "Monkey_5", "Monkey_base": ["Monkey_base_2", "Monkey_base_2_1"], "Bg": "ui_common_bg1", "Bg_spine": "beijing", "Unlock_description": "Lv.5" },
	"6": { "Skin_id": 6, "Skin_type": 2, "Unlock": 10, "Skin_name": "Jester", "Skin_description": "A circus performer who uses humor to overcome obstacles and seeks treasure to restore his family's name.", "Monkey_spine": "dh_monkey_6", "Backpack_spine": "pub_6", "Dog_spine": "dh_dog_1", "Monkey_png": "Monkey_6", "Monkey_base": ["Monkey_base_2", "Monkey_base_2_1"], "Bg": "ui_common_bg1", "Bg_spine": "beijing", "Unlock_description": "Lv.10" },
	"7": { "Skin_id": 7, "Skin_type": 2, "Unlock": 15, "Skin_name": "Slick", "Skin_description": "A sharp strategist,  charming his way through corporate challenges.", "Monkey_spine": "dh_monkey_7", "Backpack_spine": "pub_7", "Dog_spine": "dh_dog_1", "Monkey_png": "Monkey_7", "Monkey_base": ["Monkey_base_2", "Monkey_base_2_1"], "Bg": "ui_common_bg1", "Bg_spine": "beijing", "Unlock_description": "Lv.15" },
	"8": { "Skin_id": 8, "Skin_type": 2, "Unlock": 20, "Skin_name": "Regal", "Skin_description": "The wise leader of a monkey clan,  striving to build a thriving kingdom despite many challenges.", "Monkey_spine": "dh_monkey_8", "Backpack_spine": "pub_8", "Dog_spine": "dh_dog_1", "Monkey_png": "Monkey_8", "Monkey_base": ["Monkey_base_2", "Monkey_base_2_1"], "Bg": "ui_common_bg1", "Bg_spine": "beijing", "Unlock_description": "Lv.20" },
}